### PR TITLE
Fix receptor offset not changing during lane switches

### LINKED ISSUE #137: Receptor offset does not change during lane switches
### Type

Behavior

### Version

2025.611.0

### Description of the bug

title
causes issues with skins that have different shapes and hitline heights
since the hitposition also changes, its a bit expected from players that the receptors also move so the skin doesnt break

a workaround is to just make all the receptors the same height

### Screenshots/Video

size limit
https://streamable.com/flwpuv

[skin used for testing (very exaggerated case)](https://drive.google.com/file/d/1pJK38JAW9Y3brg4RmR8jM6m9wbSeUpqc/view?usp=sharing)

### PR DESCRIPTION
**Pull request by menvae**
### Fix for #137 
using Kori's skin

## Before:

https://github.com/user-attachments/assets/82129d8a-a0fb-49d4-a58a-f625500d0589

## After:

https://github.com/user-attachments/assets/82237a63-9a08-420a-89ec-1b86674ca274

Closes #137

### CODE REVIEW

File: fluXis/Screens/Gameplay/Ruleset/Playfields/Playfield.cs [hunk 1]
```diff
@@ -150,6 +150,7 @@ protected override void Update()
         updatePositionScale();
 
         hitline.Y = -laneSwitchManager.HitPosition;
+        Receptors.Padding = new MarginPadding { Bottom = laneSwitchManager.ReceptorOffset };
```
Comment (flustix) [inline fluXis/Screens/Gameplay/Ruleset/Playfields/Playfield.cs]: Don't know about replacing this every frame... There has to be a better way, probably checking if the value is already the target one.

**Review by flustix — CHANGES_REQUESTED** [review]

File: fluXis/Screens/Gameplay/Ruleset/Playfields/Playfield.cs (hunk 1 above)
Comment (menvae) [reply fluXis/Screens/Gameplay/Ruleset/Playfields/Playfield.cs]: You actually clutched it
We are so back
8eda044

**Comment by flustix** [comment]
I was more thinking of comparing the current `Receptors.Padding.Bottom` with `laneSwitchManager.ReceptorOffset` and apply a new padding if they differ.

**Comment by menvae** [comment]
> I was more thinking of comparing the current `Receptors.Padding.Bottom` with `laneSwitchManager.ReceptorOffset` and apply a new padding if they differ.

Honestly I was thinking of the same thing but I thought it'd be cleaner and better if it applied the padding only when it actually changes
<details>
  <summary></summary>
  
  I have ptsd from comparing floats
  Comparing floats is unreliable and if we cast to an int it would be inaccurate because of the interpolation
</details>

**Comment by flustix** [comment]
> I have ptsd from comparing floats Comparing floats is unreliable and if we cast to an int it would be inaccurate because of the interpolation

[`Precision.AlmostEquals`](https://github.com/InventiveRhythm/osu-framework/blob/44c1651b008455cc48444d9e5d43018e6d2ba9ab/osu.Framework/Utils/Precision.cs#L68)

**Comment by menvae** [comment]
> > I have ptsd from comparing floats Comparing floats is unreliable and if we cast to an int it would be inaccurate because of the interpolation
> 
> [`Precision.AlmostEquals`](https://github.com/InventiveRhythm/osu-framework/blob/44c1651b008455cc48444d9e5d43018e6d2ba9ab/osu.Framework/Utils/Precision.cs#L68)

{505F95A4-B88E-4395-B0C8-94FE82107145}

**Comment by menvae** [comment]
Now I feel dumb...
